# Generated by Django 6.0.5 on 2026-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
