# Generated by Django 6.0.5 on 2026-06-06 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_delete_after_file_is_temporary_alter_file_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('total_space', models.BigIntegerField(default=0)),
                ('used_space', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('chunk_size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='files.file')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='ChunkReplica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replicas', to='files.filechunk')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.storagenode')),
            ],
        ),
    ]
