# Generated by Django 6.0.5 on 2026-06-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_storagenode_filechunk_chunkreplica'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagenode',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
