# Generated by Django 6.0.5 on 2026-06-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_storagenode_last_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_distributed',
            field=models.BooleanField(default=False),
        ),
    ]
