# Generated by Django 6.0.5 on 2026-06-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_is_distributed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chunkreplica',
            constraint=models.UniqueConstraint(fields=('chunk', 'node'), name='unique_chunk_node'),
        ),
    ]
